apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBWiABjIsbQ78ihNrJu5xWj2N6PVyXCg/zXzr/4MlN9OpPtw1httS1nnv1+7JKBstfjDfGtivVmZ1vAn+q9xDZrAbR6w91onN18rb0B5NYJavkSmbe0uzeQiSVzH832s6F/ph4BA15EN7IIOSmiThyJksZQVQozB/azvE1kMsM4a6zogr1PPwo/pHjWiJXu3R9pLK1M2Zz7IoAxnH/frqqtldurbRBw5JAhu6sPh3KJxYnZ7lSWDt3D1lKRYhfhWKkMaSKos/p5dbJFOr5xsim6krl8nDi5Xs1UIk6MBBb8GxdSlNAClKqrce5nbiD/nbT9HACAuFAPBOk33AtOKmaoVThy92hSCqWbZYgJsR/Qn8a8BoZnWqZ7wbspKwfsu46ARwK0uAOmMVgWeBYDPnQ1WXvO2+9j7RRXDgDVeEa9Ve8pJUtVhj7Kah1Fm/+Bg+XVTqKA8MAzg7n+nO7Uqrqo7ETCCTFJIiToGZJQ36nOIo9A9BSXJGolZibk4vU9rFQ0AGN1hjHxWhpKlm2fYObgTepEpdk08ZxGdVM/Yr1MV7yBdIaObc6djSPUFSYCuijVwRMYZzyNxta+rTcxK869uD62tVHcszT5HnOdszD1/T0rTfXtmZ7eTSrGs1ft9c9LrQxhiDPoLKfVa6+F39MxpbJiXK0V8wsbT04dt03tMsJoYbmWtkKTVxG2bxJFMUTsrX+PxB/UJjN3bGESHmdUPYThniPQjuSnUVeuT7wzYmtzzRPwnFwT
  template:
    metadata:
      name: cloudflare-dns-api-token
      namespace: cert-manager
    type: Opaque
