apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: immich
  namespace: immich
spec:
  gatewayClassName: cilium
  listeners:
  - hostname: immich.seigra.net
    name: immich
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - kind: Secret
        name: immich-gateway-tls
      mode: Terminate
