apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich
  namespace: immich
spec:
  hostnames:
  - immich.seigra.net
  parentRefs:
  - name: immich
  rules:
  - backendRefs:
    - name: immich-server
      port: 80
