# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

components:
- ../../../shared/components/strip-helm-labels

helmCharts:
- name: csi-driver-smb
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  releaseName: csi-driver-smb
  namespace: kube-system
  version: 1.19.1

images:
- name: registry.k8s.io/sig-storage/livenessprobe
  newTag: v2.17.0@sha256:9b75b9ade162136291d5e8f13a1dfc3dec71ee61419b1bfc112e0796ff8a6aa9
- name: registry.k8s.io/sig-storage/csi-node-driver-registrar
  newTag: v2.15.0@sha256:11f199f6bec47403b03cb49c79a41f445884b213b382582a60710b8c6fdc316a
- name: registry.k8s.io/sig-storage/smbplugin
  newTag: v1.19.1@sha256:4e4a286490bb9d0f6de35a9486d117bb7ba8a352f1e7532420b7c9ac2c565087
- name: registry.k8s.io/sig-storage/csi-provisioner
  newTag: v5.3.0@sha256:bb057f866177d5f4139a1527e594499cbe0feeb67b63aaca8679dfdf0a6016f9
- name: registry.k8s.io/sig-storage/csi-resizer
  newTag: v1.14.0@sha256:5e7cbb63fd497fa913caa21fee1a69f727c220c6fa83c5f8bb0995e2ad73a474
