# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- client.yaml
- roles.yaml
- protocolmapper.yaml
- oidc-secret-sync.yaml

labels:
- pairs:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: keycloak
  includeSelectors: true
  includeTemplates: true
