# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx-tika
spec:
  ports:
  - name: tika
    port: 9998
