apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/name: velero
  name: node-agent
  namespace: velero
spec:
  selector:
    matchLabels:
      name: node-agent
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: velero
        app.kubernetes.io/name: velero
        name: node-agent
        role: node-agent
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - node-agent
        - server
        - --features=EnableCSI
        command:
        - /velero
        env:
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/cloud
        - name: AZURE_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: ALIBABA_CLOUD_CREDENTIALS_FILE
          value: /credentials/cloud
        image: docker.io/velero/velero:v1.17.1@sha256:58f551f0d89a9ef1919771bdc7475c08bc1795a50a51a57b5f14316d68fc3baa
        imagePullPolicy: IfNotPresent
        name: node-agent
        ports:
        - containerPort: 8085
          name: http-monitoring
        securityContext: null
        volumeMounts:
        - mountPath: /credentials
          name: cloud-credentials
        - mountPath: /host_pods
          mountPropagation: HostToContainer
          name: host-pods
        - mountPath: /host_plugins
          mountPropagation: HostToContainer
          name: host-plugins
        - mountPath: /scratch
          name: scratch
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 0
      serviceAccountName: velero-server
      terminationGracePeriodSeconds: 3600
      volumes:
      - name: cloud-credentials
        secret:
          secretName: velero
      - hostPath:
          path: /var/lib/kubelet/pods
        name: host-pods
      - hostPath:
          path: /var/lib/kubelet/plugins
        name: host-plugins
      - emptyDir: {}
        name: scratch
