apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero
  namespace: velero
spec:
  encryptedData:
    cloud: AgCpN59IgSaQkpmx2OU3CINfW3gQhdtEkS1GFDcn1hywPKJvzgzshD1YFtdeuILTI9O1PbaheuGHycqw/sNj1YLXTcxicR9A78tw+JpQPgnYXSLDXd40Z6ABt1zmbkJxMyoJNPMBfbqh7aNum6Z5QYar/RgDrkjG6o/CXx+JzXIwbGBo3MCXDBfL6pgZL/y95qtaQ33Tfu6dSaziy9ybcGi2KroiTEyc91pjzy8JfLZxUG6Aaqa5Q40wYHELKBaiREc4oMixPN+ofsyY8C0WLvpqbK4ECKAXeug5qpga+rxZsLb3S2MC9EOm2sEfMV94VnF6v3u+/8dAOcCb7OxP8T9fGGxwyS5aOA8gy24RIJnuI8Gfs3cQuG2B6k0cLxF6nPVMQuEB6u32kJ8RMoNldf2zt5BFTa0o2TZtufH9XLflq7AXRi5k0GA2xnmxiUwVEs7CpjaeIEz+HDnR6AbWfhkmG68+9LidR3qPBmiTlH+5ixs1kXQI1xx55rr4W9EOP47FqIZzlL5QMsMWc7k341jFFZVIZl9koQC6AB+b6qLk12sEHf0ebJgGk4hoaIw9TnyD+qEAbZm+aLeBM4ebJXnMjkomxl1xm8ov3aj1OU8tSlnZ9nBcD+2NkzTzUxyc1fQtzw0hA6ObXVttgwebL+blgX4OdiAOhQugfFeBVT+rv+PYnykdcMmQeEtcYgbD8NNePhYhBCL1Ffg4N8RzNYg4FoNSW5dJULS8AKkUA+KOH330zmsgqWHIcwG/M7+U1J51mnVXVNposiQ13oGKteKpaer1a6TCLofyjWu9BU6TA4afYNy19rgvnLz3fqDuSRVhGVLldgtq2Pp+ujPzXFd1PELs
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: velero
        app.kubernetes.io/name: velero
      name: velero
      namespace: velero
    type: Opaque
