apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-s3-credentials
  namespace: keycloak
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAy3yinrMxAtAD92Tlli+kfIpSWvW9/gvukQ1LPZe9d74RTcy42UCtMEbBNGeeVIV66FZA+6Lardef/PgkNnSsDyL0hAOYpsAufhpgQ+4ClJlDgnVJn4jRg9L+Tyvjn5LlHXh7QzmjyUvJCPm9yF5JwusUE7AC+qdqv1Ng1slzX0y7v4VAF8Fh8Qa3KNZsjZ5gg/5eANNwu6817pTeGoQRc+nhEWBKmwj3kAVPIoCf1g/vqcyuiLbozJ+BPAJrGnIGz7HFSOcM3Fw+4saSS9TFB47Wo6XS14QXd4ISya0YPfqQkuwxa3Z0rmd/aMebp3qDAaRU/VnB+aKAjvZRF5h4CXBuWxZk9FDCtFd7OODygrn1RPvTUKQKNjRqpvcsCqT0aaiz1DNUJcfoLqFT2plc3rQV4sZrNplWkwUmX7Zb3kXmwRUb5xQCetllGVQBFxDRGDQmT1ble+Vq2iQ1IZArR4uIg0P0fQKdGomEKOC8Ef5JHCa8xafAPP+hpVeBfhSlBUcaA6UHhjV6s4XMk1I70As3hBu7qIuZoJJfhUUBz2300M+FqyMCbd50W+TNMryfN2jPhcfc/Kvt4WGElKcPttytrRFMnEUjTKuN1i9YA8GdQI+qsppnX2rtcFewVCFahwUxTnOCla7afsmU8sz7oG4ri/8uftzk85XTNMAfWIYu7mYI+jDfaGk9x9z/+7+V8TQiZTNCR7eRPxktceuPVn+tuUw==
    ACCESS_SECRET_KEY: AgC9sNzwneUNL/XqQu3z6mg5ZLRipr1RyQADfkxabGYmAO+flDxByNLbFyjEAItauNyU2aufZu1SAgK8iSlfnuVwZtVyHPlqdZYnh4Vp+EB8cAcFW/PBu1ovoOVeIHEwINWqBPInjxyRhmS9nlcUi0c1fsYhVuT9Mnl4QnIKRQbUKKyqU/IIeD9V3pZ7UIk9ze8v1+PjnLSIAhG8k/akpwQIQOZMfsYxhs+8wnP6xvkWBQli/4vOduI7eRvQxARwaYyGas9EFFqJTxHGa+CHJ6e8VeHeoLASZgmliAOVbtLOCq7pv6l/KSqrLkxE46bMYmrea6pfH2bcYXB0qw3trjUftzpj3Hqpv2kC6tGqnj4D3XV/wJgf7r25QaE6F+THfbtkvEUXqqiZEMFF7jA6HEKaHInNWGOsU6pVoJ/fQLMj5V51upAxsWlELtecUcyM30W94M4sANC+z6OLJu5kwRtFmTiy1woILdlDlbFC08vWXSt1dbgQHd13ajZjJfx7Tye+FBErZ9vAa/YbohSYTLsHlzxFAJymjGCv0vb8HEdc14B3hUBP30Q5tmZJVe2SBJ+5gXf8ra/4kiI2aXzCRNj5/tJRHqe3UyHGLM1Zjh3G2KMdcian4vtU5l7t9pGLZnZWMf5rRVwUvudizIRhrlOXp7vOSg95+kd1tlh8+j4Jit3MD+Xr+EL1DZaFGCZn4cWPLNCJ/E8f7+20BqcTtVu1hgFcg+7fFYOSi9PdV3xGE9H13yDzvEXN
  template:
    metadata:
      name: keycloak-db-s3-credentials
      namespace: keycloak
    type: Opaque
