apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgCICodUScoAzi9FnS9KICVyWt397LRXlRZgvYi5qtwbRunZlmvOdJq9+B/RtGkh0AgDmptJGLMAUuWHpBxehVyxiEoC31iUm6GQeqt/BWIgiOSsgvfcoyXPtNOuAhyRsBeReglVVu80G/xCt/aSatDs9fysWUjYdrhAlg+FjfN7xuFx/GYINdSnSY2FsrPw+h0SrV8H6u/Z3uB8O7bfYFb3mxZ1e7b7ij4P6hQCW2mlCBM0LAF4HN3LX5KaVq54CJxYcinfHHGmmAls07Q0BAeYbyLbul5gddy/WvQmpDIqCmIrTrgr7fRs2Dn30b1SHW91O+RWhjPDIh8RMX+sX0fnxUODM8asNEosEF/b4DS8foUv2KCn2qWeQoZnP35mnAuEvymnGXeeetzDVhvhhoItHFSL0n++XeBve42sOb1v3bQXgWsv5DM2403IZVReKuosJUb49HEQu0bu2bA3NS+P1XC636Xolc/pUSTWQiJsFo2WeWiHyr/rpvNzdaUZTGjQm3LwEDV4lEzdnn/A8MtRwDrPS0K2l/Evp0so0NVPXhkx33B6VCf2u8qSzRRA+IGmZ2/JAGE8EopzRGCs4b+ZSKv59zZAx3Vu/DGq6OezMZ83kBYIZcQ6+69IxVwzmg2sE9/E5KmK4JmQYY6Zg3Rs8ir0IOS/25RrvFwYpQOJrFaM8QRuWA3t4Ltjg5Po4qYSIv6/qYcm7KtInwpPn2WY79AWSyXIVaDIlaXPYiW6Kw==
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloak
    type: Opaque
