apiVersion: authenticationflow.keycloak.crossplane.io/v1alpha1
kind: Execution
metadata:
  name: home-webauthn-kerberos
spec:
  deletionPolicy: Orphan
  forProvider:
    authenticator: auth-spnego
    parentFlowAliasRef:
      name: home-webauthn
    priority: 2
    realmId: home
