apiVersion: authenticationflow.keycloak.crossplane.io/v1alpha1
kind: Execution
metadata:
  name: home-webauthn-forms-passwordless
spec:
  deletionPolicy: Orphan
  forProvider:
    authenticator: webauthn-authenticator-passwordless
    parentFlowAlias: webauthn forms
    priority: 2
    realmId: home
    requirement: REQUIRED
