apiVersion: authenticationflow.keycloak.crossplane.io/v1alpha1
kind: Execution
metadata:
  name: home-webauthn-identity-provider-redirector
spec:
  deletionPolicy: Orphan
  forProvider:
    authenticator: identity-provider-redirector
    parentFlowAliasRef:
      name: home-webauthn
    priority: 3
    realmId: home
    requirement: ALTERNATIVE
