apiVersion: authenticationflow.keycloak.crossplane.io/v1alpha1
kind: Flow
metadata:
  name: home-webauthn
spec:
  deletionPolicy: Orphan
  forProvider:
    alias: webauthn
    description: passkey authentication
    realmId: home
