apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  hostnames:
  - auth.seigra.net
  parentRefs:
  - name: keycloak
  rules:
  - backendRefs:
    - name: keycloak
      port: 8080
