apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: admin-group-roles
  namespace: keycloak
spec:
  forProvider:
    groupIdRef:
      name: home-admins
    realmIdRef:
      name: home
    roleIdsRefs:
    - name: argocd-admin
      namespace: argocd
    - name: grafana-admin
      namespace: monitoring
    - name: kubernetes-cluster-admin
      namespace: kube-system
