apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-public
  namespace: keycloak
spec:
  hostnames:
  - auth.seigra.net
  parentRefs:
  - name: keycloak
  - name: keycloak-cloudflare
  rules:
  - backendRefs:
    - name: keycloak
      port: 80
    matches:
    - path:
        value: /realms/home
    - path:
        value: /resources
