apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: home-members
  namespace: keycloak
spec:
  deletionPolicy: Orphan
  forProvider:
    name: Members
    realmIdRef:
      name: home
