apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: home-admins
  namespace: keycloak
spec:
  deletionPolicy: Orphan
  forProvider:
    name: Admins
    realmIdRef:
      name: home
