apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
  name: keycloak-db
  namespace: keycloak
spec:
  affinity:
    podAntiAffinityType: required
  bootstrap:
    recovery:
      database: keycloak
      source: origin
  externalClusters:
  - name: origin
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: keycloak-db
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-standard-trixie@sha256:441cda9cd1b2ba50d45245f6498ec39a0ad97a7532e9eb159004a1d1cc856749
  instances: 3
  plugins:
  - isWALArchiver: true
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: keycloak-db
  storage:
    size: 100Gi
    storageClass: ssd-r1
