apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cdi-clone-source
  namespace: virtualmachines
spec:
  egress:
  - ports:
    - port: 8443
    to:
    - podSelector:
        matchLabels:
          cdi.kubevirt.io: cdi-upload-server
  podSelector:
    matchLabels:
      cdi.kubevirt.io: cdi-clone-source
  policyTypes:
  - Egress
