apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: virtualmachine-egress
  namespace: virtualmachines
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.244.0.0/16
        - 10.96.0.0/12
  podSelector:
    matchLabels:
      kubevirt.io: virt-launcher
  policyTypes:
  - Egress
