apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/version: 1.3.0
  name: redis-operator
  namespace: redis-operator
spec:
  endpoints:
  - interval: 15s
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis-operator
      app.kubernetes.io/name: redis-operator
