# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../shared/components/strip-helm-labels

helmCharts:
- name: sealed-secrets
  repo: https://bitnami-labs.github.io/sealed-secrets
  releaseName: sealed-secrets
  namespace: kube-system
  version: 2.18.0
  includeCRDs: true
  valuesInline:
    fullnameOverride: sealed-secrets-controller
    image:
      registry: ghcr.io
      repository: bitnami-labs/sealed-secrets-controller

images:
- name: ghcr.io/bitnami-labs/sealed-secrets-controller
  newTag: 0.34.0@sha256:fc98be1ebd2c290d29a04ccefb81a6acb307057085aa1232ff63dca5adb8b9bb
