# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-gateway

resources:
- https://github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.4.0
- https://github.com/pl4nty/cloudflare-kubernetes-gateway/config/default?ref=v0.8.1
- https://github.com/pl4nty/cloudflare-kubernetes-gateway/config/prometheus?ref=v0.8.1

patches:
- patch: | # Privilege namespace
    apiVersion: v1
    kind: Namespace
    metadata:
      name: cloudflare-gateway
      labels:
        pod-security.kubernetes.io/enforce: baseline

images:
- name: ghcr.io/pl4nty/cloudflare-kubernetes-gateway
  newTag: v0.8.1@sha256:cef110f9052c32f541fc652922f7befdc13dcaf947a243329ba0544e4d9b23fc
