# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-gateway

resources:
- https://github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.4.0
- https://github.com/pl4nty/cloudflare-kubernetes-gateway/config/default?ref=v0.8.1
- https://github.com/pl4nty/cloudflare-kubernetes-gateway/config/prometheus?ref=v0.8.1

patches:
- patch: | # Privilege namespace
    apiVersion: v1
    kind: Namespace
    metadata:
      name: cloudflare-gateway
      labels:
        pod-security.kubernetes.io/enforce: baseline
- patch: | # Pin cloudflared image
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller-manager
      namespace: cloudflare-gateway
    spec:
      template:
        spec:
          containers:
          - name: manager
            env:
            - name: GATEWAY_IMAGE
              # renovate: datasource=docker depName=cloudflare/cloudflared
              value: docker.io/cloudflare/cloudflared:2025.11.1@sha256:89ee50efb1e9cb2ae30281a8a404fed95eb8f02f0a972617526f8c5b417acae2

images:
- name: ghcr.io/pl4nty/cloudflare-kubernetes-gateway
  newTag: v0.8.1@sha256:cef110f9052c32f541fc652922f7befdc13dcaf947a243329ba0544e4d9b23fc
