apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: ezxss
    app.kubernetes.io/instance: ezxss
    app.kubernetes.io/name: ezxss
    app.kubernetes.io/part-of: ezxss
  name: ezxss
  namespace: ezxss
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ezxss
      app.kubernetes.io/instance: ezxss
      app.kubernetes.io/name: ezxss
      app.kubernetes.io/part-of: ezxss
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ezxss
        app.kubernetes.io/instance: ezxss
        app.kubernetes.io/name: ezxss
        app.kubernetes.io/part-of: ezxss
    spec:
      containers:
      - env:
        - name: EZXSS_DBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: ezxss-db-password
        envFrom:
        - configMapRef:
            name: ezxss
        image: ghcr.io/gadgetmg/ezxss:master@sha256:852da30cac7215e05caa7be3b16ea5828bc4132006f2566f2e60b858f5d18c76
        name: ezxss
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 33
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
