apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: kubernetes
  namespace: kube-system
spec:
  forProvider:
    accessType: PUBLIC
    clientId: kubernetes
    fullScopeAllowed: false
    realmIdRef:
      name: home
      namespace: keycloak
    standardFlowEnabled: true
    validRedirectUris:
    - http://localhost:8000
    - https://headlamp.seigra.net/oidc-callback
