apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  labels:
    seigra.net/roles: admin
  name: kubernetes-cluster-admin
spec:
  deletionPolicy: Orphan
  forProvider:
    clientIdRef:
      name: kubernetes
    description: kubernetes cluster-admin
    name: cluster-admin
    realmIdRef:
      name: home
