apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: gotenberg
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/name: paperless-ngx-gotenberg
    app.kubernetes.io/part-of: paperless-ngx
  name: paperless-ngx-gotenberg
  namespace: paperless-ngx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: gotenberg
      app.kubernetes.io/instance: paperless-ngx
      app.kubernetes.io/name: paperless-ngx-gotenberg
      app.kubernetes.io/part-of: paperless-ngx
  template:
    metadata:
      labels:
        app.kubernetes.io/component: gotenberg
        app.kubernetes.io/instance: paperless-ngx
        app.kubernetes.io/name: paperless-ngx-gotenberg
        app.kubernetes.io/part-of: paperless-ngx
    spec:
      containers:
      - command:
        - gotenberg
        - --chromium-disable-javascript=true
        - --chromium-allow-list=file:///tmp/.*
        image: gotenberg/gotenberg:8.25.0@sha256:e304e45acee3c400f8ef76afa195c76b1d0eaf0ab6fe9651e305067ab6a1560c
        name: gotenberg
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 1001
          runAsUser: 1001
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
