apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/name: paperless-ngx-redis
    app.kubernetes.io/part-of: paperless-ngx
  name: paperless-ngx-redis
  namespace: paperless-ngx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/instance: paperless-ngx
      app.kubernetes.io/name: paperless-ngx-redis
      app.kubernetes.io/part-of: paperless-ngx
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
        app.kubernetes.io/instance: paperless-ngx
        app.kubernetes.io/name: paperless-ngx-redis
        app.kubernetes.io/part-of: paperless-ngx
    spec:
      containers:
      - image: ghcr.io/valkey-io/valkey:9.0.0-alpine3.22@sha256:b4ee67d73e00393e712accc72cfd7003b87d0fcd63f0eba798b23251bfc9c394
        name: redis
        readinessProbe:
          tcpSocket:
            port: 6379
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 999
          runAsUser: 999
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
