apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: tika
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/name: paperless-ngx-tika
    app.kubernetes.io/part-of: paperless-ngx
  name: paperless-ngx-tika
  namespace: paperless-ngx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: tika
      app.kubernetes.io/instance: paperless-ngx
      app.kubernetes.io/name: paperless-ngx-tika
      app.kubernetes.io/part-of: paperless-ngx
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tika
        app.kubernetes.io/instance: paperless-ngx
        app.kubernetes.io/name: paperless-ngx-tika
        app.kubernetes.io/part-of: paperless-ngx
    spec:
      containers:
      - image: docker.io/apache/tika:3.2.3.0@sha256:c0154cb95587cde64be74f35ada1a2bd7892219f3f0ac3c9dc6cab34046b3573
        name: tika
        readinessProbe:
          httpGet:
            port: 9998
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
