apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/component: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/part-of: paperless-ngx
  name: paperless-ngx-secret-key
  namespace: paperless-ngx
spec:
  dataFrom:
  - rewrite:
    - transform:
        template: secret_key
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: paperless-ngx-secret-key
  refreshInterval: 0s
  target:
    template:
      data:
        PAPERLESS_SECRET_KEY: '{{ .secret_key }}'
