apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/name: paperless-ngx-db
    app.kubernetes.io/part-of: paperless-ngx
  name: paperless-ngx-db
  namespace: paperless-ngx
spec:
  affinity:
    podAntiAffinityType: required
  bootstrap:
    recovery:
      database: paperless-ngx
      source: origin
  externalClusters:
  - name: origin
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: paperless-ngx-db
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-standard-trixie@sha256:9b352c7e9f1095e9567c537e058d49d8e1a6495ee56ed8dbd832d602e689ccc6
  instances: 3
  plugins:
  - isWALArchiver: true
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: paperless-ngx-db
  storage:
    size: 100Gi
    storageClass: ssd-r1
