apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-keycloak
spec:
  package: ghcr.io/crossplane-contrib/provider-keycloak:v2.14.0@sha256:5a04936293889fcbe21ab941ccff586493ab2edd29acdf7a90d97cb28b0c59c2
  runtimeConfigRef:
    name: provider-keycloak
