apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: argocd
spec:
  deletionPolicy: Orphan
  forProvider:
    accessType: CONFIDENTIAL
    clientId: argocd
    fullScopeAllowed: false
    realmIdRef:
      name: home
    rootUrl: https://argocd.seigra.net
    standardFlowEnabled: true
    validRedirectUris:
    - https://argocd.seigra.net/api/dex/callback
  writeConnectionSecretToRef:
    name: argocd-oidc-secret
    namespace: crossplane-system
