apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    cert-manager.io/cluster-issuer: letsencrypt
  name: argocd
  namespace: argocd
spec:
  gatewayClassName: cilium
  listeners:
  - hostname: argocd.seigra.net
    name: argocd
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - name: argocd-gateway-tls
      mode: Terminate
