apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
  namespace: piraeus-datastore
spec:
  highAvailabilityController:
    podTemplate:
      spec:
        containers:
        - args:
          - /agent
          - --v=1
          - --disable-node-taints=true
          name: ha-controller
  linstorPassphraseSecret: linstorcluster-passphrase
