apiVersion: v1
data:
  ACTUAL_ALLOWED_LOGIN_METHODS: openid
  ACTUAL_LOGIN_METHOD: openid
  ACTUAL_OPENID_AUTH_METHOD: oauth2
  ACTUAL_OPENID_CLIENT_ID: actual
  ACTUAL_OPENID_DISCOVERY_URL: https://auth.seigra.net/realms/home
  ACTUAL_OPENID_SERVER_HOSTNAME: https://actual.seigra.net
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: application
    app.kubernetes.io/instance: actual
    app.kubernetes.io/part-of: actual
  name: actual-server-env-fkmtk95ctt
  namespace: actual
