# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- providers/keycloak/provider.yaml
- providers/keycloak/deploymentruntimeconfig.yaml
- mrap.yaml
