# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- https://github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.4.0
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.5.4/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backends.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.5.4/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.5.4/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.5.4/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.5.4/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoypatchpolicies.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.5.4/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.5.4/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_httproutefilters.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.5.4/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml

components:
- ../../../shared/components/strip-helm-labels

helmCharts:
- name: gateway-helm
  repo: oci://docker.io/envoyproxy
  releaseName: envoy-gateway
  namespace: envoy-gateway-system
  version: 1.5.4
  valuesInline:
    config:
      envoyGateway:
        extensionApis:
          enableBackend: true
