# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.10.0/manifest.yaml

components:
- ../../../shared/components/strip-helm-labels

helmCharts:
- name: cloudnative-pg
  repo: https://cloudnative-pg.io/charts
  releaseName: cnpg
  namespace: cnpg-system
  version: 0.27.0
  valuesInline:
    replicaCount: 1

images:
- name: ghcr.io/cloudnative-pg/plugin-barman-cloud
  newTag: v0.11.0@sha256:c2788d1560118926302a21159b4b0452fc133df1a3f957c1b2ed6b41834ee571
- name: ghcr.io/cloudnative-pg/cloudnative-pg
  newTag: 1.28.0@sha256:34198e85b6e6dd81471cb1c3ee222ca5231b685220e7ae38a634d35ed4826a40
