# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mariadb-system

resources:
- namespace.yaml

components:
- ../../../shared/components/strip-helm-labels

patches:
- patch: |
    - op: add
      path: /metadata/namespace
      value: mariadb-system
  target:
    kind: (ValidatingWebHookConfiguration|Deployment|ServiceMonitor|RoleBinding|Role|ConfigMap|ServiceAccount|Service)

helmCharts:
- name: mariadb-operator
  repo: https://mariadb-operator.github.io/mariadb-operator
  releaseName: mariadb-operator
  version: 25.10.2
  includeCRDs: true
  valuesInline:
    crds:
      enabled: true
    image:
      repository: ghcr.io/mariadb-operator/mariadb-operator
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    webhook:
      enabled: true
      serviceMonitor:
        enabled: true
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    certController:
      serviceMonitor:
        enabled: true
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
