# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/v4.2.3/deployments/multus-daemonset-thick.yml

images:
- name: ghcr.io/k8snetworkplumbingwg/multus-cni
  newTag: v4.2.3-thick@sha256:e93af9e533cc16ca7847aeec3b516c9b1e8891c2b95c727991e94c9b59c4970e

patches:
- path: patches/memory-limit-fix.yaml
- path: patches/install-binary-fix.yaml
- path: patches/talos-host-run-netns.yaml
