apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: core
    app.kubernetes.io/part-of: harbor
  name: harbor-core
  namespace: harbor
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: core
      app.kubernetes.io/instance: harbor
      app.kubernetes.io/name: core
      app.kubernetes.io/part-of: harbor
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/component: core
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/name: core
        app.kubernetes.io/part-of: harbor
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: core
                app.kubernetes.io/instance: harbor
                app.kubernetes.io/name: core
                app.kubernetes.io/part-of: harbor
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      containers:
      - env:
        - name: JOBSERVICE_SECRET
          valueFrom:
            secretKeyRef:
              key: JOBSERVICE_SECRET
              name: harbor-jobservice
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: harbor-db-app
        envFrom:
        - configMapRef:
            name: harbor-core-2fcdc2d52d
        - configMapRef:
            name: harbor-common-kbtct2g5dm
        - secretRef:
            name: harbor-core
        - secretRef:
            name: harbor-common
        - secretRef:
            name: harbor-config-override
        image: goharbor/harbor-core:v2.14.0
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/v2.0/ping
            port: 8080
            scheme: HTTP
          periodSeconds: 10
        name: core
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/v2.0/ping
            port: 8080
            scheme: HTTP
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          failureThreshold: 360
          httpGet:
            path: /api/v2.0/ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - mountPath: /etc/core/app.conf
          name: config
          subPath: app.conf
        - mountPath: /etc/core/key
          name: key
          subPath: key
        - mountPath: /etc/core/private_key.pem
          name: token
          subPath: tls.key
        - mountPath: /etc/core/token
          name: psc
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          items:
          - key: app.conf
            path: app.conf
          name: harbor-core-conf-m8f489mbkm
        name: config
      - name: key
        secret:
          items:
          - key: key
            path: key
          secretName: harbor-core-key
      - name: token
        secret:
          secretName: harbor-core-token-tls
      - emptyDir: {}
        name: psc
