apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-common
  namespace: harbor
spec:
  encryptedData:
    REGISTRY_CREDENTIAL_PASSWORD: AgBHrcoRa3fni4thevdoqDso+Rc38t3sJPvG8AtxrmV4jfoUx+swHXdwOCgN+evznKNSkOMvpcVe67vAHJt2xd1qUDqDghh/TUE1ApRLVGy4xrC+QqknxBzuPQ+SwJi5xYsAaXEZes6YkjpP5I3Pt2mzJcTs3I6ut4qpeN4xF36uxI628pdYLfasFhGp1iJfRaNgqdc3hR1xBNQggsOKEMgzoAloi/nhZzrNwFjl/cUeAtu+uy3ENf7u6cUuIOsjiPat1RbG61C+PbVbGnpTyfLpMCPQg1U4F8XvrRiIaIboMbfToLwI1wnSTk2ZwMSnxg7CZIn+KgecBpUC5spS7oUMv2MFU1tmCeDQXnNslwHRkSs0OHuv9X2qy23yPwrehDfnn8H4HFt+pt898PVK98W5EpcHkBzcroOPolotnj906OoT+rMOihupnqR11vVnZapDZBnYbqmwgBI4mkhx0NvtxuAy//0apoTeNiGPqzddb8xGyBCHtC92hZ19UMSDQznGcz+M5HIStDxgqZ+ewoKRXghIwe0RfDskpHoMpnrJBAK5Veejp165b2ThKg1jIYJGqop0tfCut/qKn/yiwP7j22XWnLYgw/TpxMKPEcfsWskfmAp+Eecz0FBSDcIo31BC0zOqDVApO36uVtcYly33GkOnudwcJRLB9hJ7+iQWnd/BlRYx1QTpvreWdtYjtg1svieFjozqLI0fO78QgasCU+C5WW5MmUWXfWd+3WRSKA==
  template:
    metadata:
      name: harbor-common
      namespace: harbor
