apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-jobservice
  namespace: harbor
spec:
  encryptedData:
    JOBSERVICE_SECRET: AgAAr8QmbCHGQn3nl+irJUj7yGybut6i6yXOHaz5rx3qyfoMMbzqHtoW1Oyk9gk2Gw7BydKrXSMSSpp+UfiEv7jYse1KWNCKBEs9lSLeF5d7Ju95935e2354Qq37TqYtKXWRh1gpsAefCnv1xq40eH7F6L+HmM2Hpkp/RAqQvPm/b8qBiLEOLe35omdPRa8mNvFnOTigKu5jiEaHfWNLiYtoHvZRlhzu/hAUSlVc/MxVPgDC+KkHaSeDcjT6zGZZM43baJgFPW3Yf34BdP/wJpddjUUOsTj4+RcLuO//GHumgYanZGPEXRzs0qVNn8cpIdHGRQn5Tz308oS+006J5QL91sKxA7H0enl+lZOSEzbUlO19CXu54+YyROYYOOVTQvj7KqQ/87ZPJk5qKQe63quhS2F2MIwu72clD7Zt+/36D4zK+97KsV/mF4zIA2L41LoM+JauqsFBEHwoc7WkYMfyNGppmcKfzC6UzEnAqoNVSiqXSOeLzB/gt2Zetg+GPBV50NR9pgPH2kEtrfvS40giT/9d93lBW/bkQHFxBT30f2zJ/NBwUsFZMSbaZ6Dm6B36kXZxk2ZkPoUakSN6lF27671hSej+WO3M6F3jY+RYy8wR4L+OKPuLeqqNcK3hfJGYg5AhL++Itz8b6p5xLcPxo3XDAwKWCJbopminRPZVkm2cRmrC6K49aAWrAgfYw6COlNcBfSSjpNv/Km9gBd4P
  template:
    metadata:
      name: harbor-jobservice
      namespace: harbor
