apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-core-key
  namespace: harbor
spec:
  encryptedData:
    key: AgC6vxPlB12aG78ePgAsDZIy/Ge55WV9zZYH3epmZzWcjc3yBHlSwfV4askMBDXTCT1xUewwGj/MWkNrGvpgTsSo+D3qe3uQWSa/zQILAzMKfsHwrPNdJW8EwaGxIjku5yHK5b274vH+WHCjTBPRp7mXgMgB+p7opiC1Q+yaLgh3p/GaBODLAlYY13b5e24y2WcZrJLzMGkTGlOgYQAhLDMjDbG7bhg/bIBddQbjpGhvvJFj6IvmG4kz7IASNTXiCc7z7XK28Cx/ueTD0QNvTm8UAe74eC153nHVLTxnXc568AGcbempP0TLdQaFBoakNZMF6Rcpih9NtVwb7Re3QgV2RyXuo0QGA4aOmkXHqdCxYFhu93zhCj65id//Hn1Wejn60m1QuN8ruJjhSiGsUx1fMoKQjOiRW6n4Nd0FHio94Are6jI25nxr+il+mzYo8AMaozasX3WrnSogfk9ut/RUL0I8HtwJVBXpUFcJFH/UiLSbF+T9DHfbsoqtY4wOd6HlDtf1yScgnp+6eiaTJ6TfsQ+n3thNJs1I+kSzhDnEBPrPwvIaVTaLjFO+Vp8f5tAJoLBXGp+glcfz7bIWg7pMn6KcYRZduhqzTAnfV0iU8XVO8bSF220pKZtEYnNp73ID2jZdCkB+saXtE3wcMOoUR524TK27P0Rk4lzfg4xx5tZO+ylIicGJoeEYeMrLEEObIY/PtF46MICu9fvG5uht
  template:
    metadata:
      name: harbor-core-key
      namespace: harbor
