apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-registry-passwd
  namespace: harbor
spec:
  encryptedData:
    passwd: AgB1f9A6Q45yLpJDnSShCofd+RxqE+ciYa33utPjEc0hQCJQjHkjSRYFnNpayDopfzXC5BSMmqK+PPVhgfdVChtZn2M8BQfAu4eAZoeShPkOztfL4NTFtmYiH+e6k4H696HywDU5fjJGcOz8wCpfHnuNIMkZbYxXZugS5HMo+JmH1gzrhLl8S3kslHSU1JVbVdDHtlcxWhTT3fSzWkJig5TVptNw4e7dx40Ey5c43HB6zQwmfPSAAH1auBr11rOjkQsJN4OIuzEeExD71Kh/0DB9hhPHhfusCcca27bL7orSrMI1yavThJseSUyLpmT60l2IOJORh6dWy+NMQFWoZbg+8nnwi+H7Uxsnchk7748RJ8sA3/yMHkEgDDFuxo/s34AWuYMG8d0useYAhG+VHMjGfKQAhaVKHOr+JCPBmxxUJov5m1fk2C1su58Ujnvy0vTTSwCUgWUPSja75F7BT/Dm2witg4+rS019R8jPNrgoWZpdP7tO7UFNLLwSx5Kr4ED7Xba3zeOAT6rjE+/axu7sFxux3FL8hV/b/THA63xfOYbKZFaHl/FoyGjGXFnfiUcy8qne91WGzFrcRSVihr14GiBW7DX7+5iZJgHjEq32+VMDp54wLl61On/lbA9L37gJDrJOiLA2UPd2mNfUmZlzpiy4021m+fCdsIsTcScvpekodeQsT4W/SRLXfrPlVjmux/+HR0ZCaOBUFF7h8qp3VlqqcUj1MKYUsDOnwRRPIHEIeOou8FyxLXTInOMdcF9dmVgiyQH+lp9j3Qs/JhTHXj8dOZouVbpxdIf7z7gqGEo=
  template:
    metadata:
      name: harbor-registry-passwd
      namespace: harbor
