apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  encryptedData:
    REGISTRY_HTTP_SECRET: AgAv7zuK2NWjca1bge6GwEafefzKHOYCtvSUEz9PfJrZE49VMJeORNio1LC4n7sHHS6ITMnNJqqxXUJgnbkGc/ElrpIb6xAoIsrr+7r+dSasU4xeo+wVvd0ToJ1logUvSCFYrPPNurfs7V/Ml30Vm3HUjPCwIFhVmYm5xynixNnpfhsB1mYbZrNGrjlRpWX8UMFsmPDNZyJeoPUPyA8LTOlt/ftgLpbx3e2XU9ZvGoTiPpq7BbwlZx7gLArl3DyM41mHzZ1GyVMLJQQQ1CFDBW++LgLGAIrGJdde02UXgaAJaNZdpRgpv6aOtCVLUTj83jJqzISUnXQD5/TZFyB8FCO7RnzpCNgOzC3qVc+ItDTx17V96UiL4Xkp5qjYQhA6lkNIKaMgOorPa2AFs+N2ne9akE/Aiw7zdVOujbMXD0VEiSLaGZJuSY2dMHKJNBeOGTFwOSzrwP0A0IeUACgyi8fxZp4KM0YS8NXYpBGE/0ptz/g9CjHicJxzTW4wFSrXwqzNXXhbuRUz9tbbZUjL8pQONpAdfMs7qNCkO1AV8fKkfi4/HanH3QTlF+uuevV98Pj/bbjfyrV6xJ5PKfWfGLf4gtOf5QYXdCoMKmQ9kP9tksuDKlMmLHC+uiuYjCb7dYnjneLMYrA+FRenVrKAnRh65U3kRFu3ps+MgRvbHuH8hRvnzP9TN3qGGf5EHnZAi6gvevj69AWnplc+NN9b0rjh
  template:
    metadata:
      name: harbor-registry
      namespace: harbor
