apiVersion: client.keycloak.m.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: harbor
  name: harbor-client-roles
  namespace: harbor
spec:
  forProvider:
    clientIdRef:
      name: harbor
    config:
      access.token.claim: "false"
      claim.name: groups
      id.token.claim: "true"
      introspection.token.claim: "false"
      multivalued: "true"
      userinfo.token.claim: "false"
      usermodel.clientRoleMapping.clientId: harbor
    name: client roles
    protocol: openid-connect
    protocolMapper: oidc-usermodel-client-role-mapper
    realmIdRef:
      name: home
      namespace: keycloak
