apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: harbor
  name: harbor
  namespace: harbor
spec:
  gatewayClassName: cilium
  listeners:
  - hostname: harbor.seigra.net
    name: harbor
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - kind: Secret
        name: harbor-gateway-tls
      mode: Terminate
