apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: harbor
  name: harbor-db
  namespace: harbor
spec:
  affinity:
    podAntiAffinityType: required
  bootstrap:
    initdb:
      database: registry
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie@sha256:0dcea5b25003d9224c467e783087f02618d0caafdaa3fc6d296d266598c9e668
  instances: 3
  storage:
    size: 10Gi
    storageClass: ssd-r1
