apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: harbor
  name: harbor-db
  namespace: harbor
spec:
  affinity:
    podAntiAffinityType: required
  bootstrap:
    initdb:
      database: registry
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie@sha256:ba1ac5727adf0075d343706fed48b348a79a6bd0a7f90bcdcca5cfe250cc9476
  instances: 3
  storage:
    size: 10Gi
    storageClass: ssd-r1
