apiVersion: v1
data:
  CORE_URL: http://harbor-core:80
  LOG_LEVEL: info
  REGISTRY_CONTROLLER_URL: http://harbor-registry:8080
  REGISTRY_CREDENTIAL_USERNAME: harbor_registry_user
  REGISTRY_URL: http://harbor-registry:5000
  TOKEN_SERVICE_URL: http://harbor-core:80/service/token
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/part-of: harbor
  name: harbor-common-kbtct2g5dm
  namespace: harbor
