apiVersion: v1
data:
  _REDIS_URL_CORE: redis+sentinel://rfs-harbor:26379/mymaster/0?idle_timeout_seconds=30
  _REDIS_URL_REG: redis+sentinel://rfs-harbor:26379/mymaster/2?idle_timeout_seconds=30
  CHART_CACHE_DRIVER: redis
  CONFIG_PATH: /etc/core/app.conf
  CORE_LOCAL_URL: http://127.0.0.1:8080
  DATABASE_TYPE: postgresql
  EXT_ENDPOINT: https://harbor.seigra.net
  JOBSERVICE_URL: http://harbor-jobservice
  PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: docker-hub,harbor,azure-acr,ali-acr,aws-ecr,google-gcr,docker-registry,github-ghcr,jfrog-artifactory
  PORT: "8080"
  PORTAL_URL: http://harbor-portal
  POSTGRESQL_DATABASE: registry
  POSTGRESQL_HOST: harbor-db-rw
  POSTGRESQL_MAX_IDLE_CONNS: "100"
  POSTGRESQL_MAX_OPEN_CONNS: "900"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_SSLMODE: disable
  POSTGRESQL_USERNAME: registry
  QUOTA_UPDATE_PROVIDER: db
  REGISTRY_STORAGE_PROVIDER_NAME: filesystem
  REPLICATION_ADAPTER_WHITELIST: ali-acr,aws-ecr,azure-acr,docker-hub,docker-registry,github-ghcr,google-gcr,harbor,huawei-SWR,jfrog-artifactory,tencent-tcr,volcengine-cr
  TRIVY_ADAPTER_URL: http://harbor-trivy:8080
  WITH_TRIVY: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: core
    app.kubernetes.io/part-of: harbor
  name: harbor-core-2fcdc2d52d
  namespace: harbor
