apiVersion: v1
data:
  app.conf: |
    appname = Harbor
    runmode = prod
    enablegzip = true

    [prod]
    httpport = 8080
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: core
    app.kubernetes.io/part-of: harbor
  name: harbor-core-conf-m8f489mbkm
  namespace: harbor
