apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: trivy
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: trivy
    app.kubernetes.io/part-of: harbor
  name: harbor-trivy
  namespace: harbor
spec:
  ports:
  - name: http-trivy
    port: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/component: trivy
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: trivy
    app.kubernetes.io/part-of: harbor
