apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: portal
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: portal
    app.kubernetes.io/part-of: harbor
  name: harbor-portal
  namespace: harbor
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/component: portal
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: portal
    app.kubernetes.io/part-of: harbor
