apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: core
    app.kubernetes.io/part-of: harbor
  name: harbor-core
  namespace: harbor
spec:
  ports:
  - name: http-web
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: core
    app.kubernetes.io/part-of: harbor
