apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/name: trust-manager
  name: trust-manager
  namespace: cert-manager
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: trust-manager
  template:
    metadata:
      labels:
        app: trust-manager
        app.kubernetes.io/instance: trust-manager
        app.kubernetes.io/name: trust-manager
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --log-format=text
        - --log-level=1
        - --metrics-port=9402
        - --readiness-probe-port=6060
        - --readiness-probe-path=/readyz
        - --leader-elect=true
        - --leader-election-lease-duration=15s
        - --leader-election-renew-deadline=10s
        - --trust-namespace=cert-manager
        - --webhook-host=0.0.0.0
        - --webhook-port=6443
        - --webhook-certificate-dir=/tls
        - --default-package-location=/packages/cert-manager-package-debian.json
        image: quay.io/jetstack/trust-manager:v0.20.3@sha256:7047bcd17f31fd381d6a6866ed991d1a21b7a4d8832cb4b11b2cdb342ffc02dd
        imagePullPolicy: IfNotPresent
        name: trust-manager
        ports:
        - containerPort: 6443
          name: webhook
        - containerPort: 9402
          name: metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6060
          initialDelaySeconds: 3
          periodSeconds: 7
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tls
          name: tls
          readOnly: true
        - mountPath: /packages
          name: packages
          readOnly: true
      initContainers:
      - args:
        - /copyandmaybepause
        - /debian-package
        - /packages
        image: quay.io/jetstack/trust-pkg-debian-bookworm:20230311-deb12u1.2@sha256:f9a6f14926da740c2831a738393f061b22594ec5d47ff55f68b1f59cfb9bf543
        imagePullPolicy: IfNotPresent
        name: cert-manager-package-debian
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /packages
          name: packages
          readOnly: false
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: trust-manager
      volumes:
      - emptyDir:
          sizeLimit: 50M
        name: packages
      - name: tls
        secret:
          defaultMode: 420
          secretName: trust-manager-tls
