apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlamp
  namespace: headlamp
spec:
  hostnames:
  - headlamp.seigra.net
  parentRefs:
  - name: headlamp
  rules:
  - backendRefs:
    - name: headlamp
      port: 80
    matches:
    - path:
        value: /
