# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  name: harbor-core
  labels:
    app.kubernetes.io/name: core
spec:
  selector:
    app.kubernetes.io/name: core
  ports:
  - name: http-web
    port: 80
    targetPort: 8080
