# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.3/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: jobservice
  name: harbor-jobservice
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: jobservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jobservice
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: jobservice
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      containers:
      - name: jobservice
        image: ghcr.io/goharbor/harbor-jobservice
        env:
        - name: CORE_SECRET
          valueFrom:
            secretKeyRef:
              key: CORE_SECRET
              name: harbor-core
        envFrom:
        - configMapRef:
            name: harbor-jobservice
        - configMapRef:
            name: harbor-common
        - secretRef:
            name: harbor-jobservice
        - secretRef:
            name: harbor-common
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/v1/stats
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/stats
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /etc/jobservice/config.yml
          name: config
          subPath: config.yml
        - mountPath: /var/log/jobs
          name: logs
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
      terminationGracePeriodSeconds: 120
      volumes:
      - name: config
        configMap:
          name: harbor-jobservice-conf
      - name: logs
        persistentVolumeClaim:
          claimName: harbor-jobservice-logs
