# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.3/service.json
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jobservice
  name: harbor-jobservice
spec:
  selector:
    app.kubernetes.io/name: jobservice
  ports:
  - name: http-jobservice
    port: 80
    targetPort: 8080
