apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cdi
  namespace: cdi
spec:
  gatewayClassName: cilium
  listeners:
  - hostname: cdi-uploadproxy.seigra.net
    name: cdi-uploadproxy
    port: 443
    protocol: TLS
    tls:
      mode: Passthrough
