# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../shared/components/strip-helm-labels

helmCharts:
- name: trust-manager
  repo: https://charts.jetstack.io
  releaseName: trust-manager
  namespace: cert-manager
  version: v0.20.2
  valuesInline:
    replicaCount: 1
    app:
      metrics:
        service:
          servicemonitor:
            enabled: true
    podDisruptionBudget:
      enabled: true
