# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../shared/components/strip-helm-labels

helmCharts:
- name: trust-manager
  repo: https://charts.jetstack.io
  releaseName: trust-manager
  namespace: cert-manager
  version: v0.20.3
  valuesInline:
    replicaCount: 1
    app:
      metrics:
        service:
          servicemonitor:
            enabled: true
    podDisruptionBudget:
      enabled: true

images:
- name: quay.io/jetstack/trust-manager
  newTag: v0.20.3@sha256:7047bcd17f31fd381d6a6866ed991d1a21b7a4d8832cb4b11b2cdb342ffc02dd
- name: quay.io/jetstack/trust-pkg-debian-bookworm
  newTag: 20230311-deb12u1.2@sha256:f9a6f14926da740c2831a738393f061b22594ec5d47ff55f68b1f59cfb9bf543
