# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.19.2/cert-manager.crds.yaml
- https://github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.4.1

components:
- ../../../shared/components/strip-helm-labels

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  namespace: cert-manager
  version: v1.19.1
  valuesInline:
    replicaCount: 1
    podDisruptionBudget:
      enabled: true
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
    dns01RecursiveNameservers: 1.1.1.1:53,1.0.0.1:53
    prometheus:
      servicemonitor:
        enabled: true
    webhook:
      replicaCount: 1
      podDisruptionBudget:
        enabled: true
    cainjector:
      replicaCount: 1
      podDisruptionBudget:
        enabled: true

images:
- name: quay.io/jetstack/cert-manager-cainjector
  newTag: v1.19.1@sha256:c7898aece8fb08102fca0b37683e37cb94e0a77c0d15b8e3c9128f6c04c868e0
- name: quay.io/jetstack/cert-manager-controller
  newTag: v1.19.1@sha256:cd49e769e18ada1fd7b9a9bacc87c90db24c65cbfd4bf71694dda7ed40e91187
- name: quay.io/jetstack/cert-manager-webhook
  newTag: v1.19.1@sha256:f5bfe77541e38978aec53cc6eb924d190e1fe923c98b2582e6ccf5edf6c02cce
