apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: cloudflare-gateway
spec:
  encryptedData:
    ACCOUNT_ID: AgCeIuHyBWHuL5dJFNKf0fImCJF+dKIOKSch34vqSv8bVdMnJEochiQ6BPzJ7iphAAuwgKVN5Km8KCSXGOejN23aBX4fRuBRrZtRda+h69H5/WufIVp8IuAT6julgr9jJMTC9nn9zcEWgSKUcyrHfoI2LFaFFv9OwXfyfBfSarrbkpLVLwldDtvwboXVpIg8aCyVzSqNdBExESVqggKyOGEoEJxak4vOCyF1k/gO2GqzPLWbSqHqi+dZADPP4xi82dATX+Wh7jgfYe0dhCo2PjjJi8rE8o1nj5NiApwn5orBT4bHnFTR/C8vEn5HWSSrADH4kKMNRY4PfQJifrQyqroj1emhRdPy2imERvAFNUkrpXBhDN67MrNpRT0FXXc8/uWt0tcyt4oB039pYhb8ugF6KxE1I7FCac15STCz0+53JFBoQhyoVlBa6MnU7Ll6dyjO+V4TQ4UVZ+75ETaoWVM4t/cFg7UluqJWbqpX8UHY0HoAMYV8LoWBaLEMOlEK4obd5B+8s91BnplEapbxGYYWOuBMRn8OuqLTokICjB0JTJBNzMNcypjsXobnDkoDkFLYTCdBumTXa8GJ7U/qfkxlEuiLOEA+Pno4kG/7QQaMCPcqU3T5vV3dT/32y2yW+SsnANTKXxuz8kLG3K9eG97RhFCIPwgeb9TpJF83Ydmp9hQ/34txpatoaSR74reQgil9cBMO+ZjEbRuDw46YlNfjlUSwZbOguKv3WHJGuiU6K9E=
    TOKEN: AgAyA/BZupGJcCXYCzwKX+YfU15Uq9INPQTM7I626eYLOSEb3l5uGaOCfIJrC8IoD1xwqYYRqIXZU9Ra6ObWnz4Yantyxl/yhioABL5ZZ/M0TUoGFja/WOgkmWQDhdwITgjFy6AIW32KVaNZyKICwq7xAD5cHDNWtHz5KJB8AsqhBu+xNLQyTnURIPCtVO07ZOlDzHTfiJNqMs1cVcjHplt+QZs0X9qWFGGR73W6yMWJCq+Bl6fO6H/USUbFouiRP0+L1odMGsL4RUpRfn62whYUcuU8GS3xFTCD4K/g64uOA2wW1RySv+z/sBwf39WZWLaXpMvRV4L/9XS4D2W+6ASH0XRclObHHC1MWxk4ow3jxqKOrXTaUjeQ7XYlN0HKeIGh4Zzym9hbByi8/E+PEWTCROPW3ADEkyu1BG9/kQvPoVDsLTyeFDYJRxtrxQBTwUH0064gmerKgkfaw4q++fK+mfyRYJSR//vaKXZBjbr5zV3rWWjc+vXAXu8j8eJOoFF08pSE+AxS+OGRZqmSTHH6MkITKiONdPSoZNiBANNrryAOhNL6x5ExWaO/uAbjm78p6MCe77Id5WiKU2Fz96UIf3shRvUxuSZ72KgE4yci+KuYsKNCv+k+jnuRXugLXGp3OuOmkwMIOnbuo8v6qCxATxopFezWLDdMYP4ixJQrfnuggG63zOPoWQxNFe8DzQTwLwU9Ypq4VmNnywDWHaETVYaPEWpXZVIP/jgrJkDeQvl74aJEDw6H
  template:
    metadata:
      name: cloudflare
      namespace: cloudflare-gateway
    type: Opaque
