# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: harbor-portal-conf
  files:
  - conf/nginx.conf

labels:
- pairs:
    app.kubernetes.io/name: portal
    app.kubernetes.io/component: portal
  includeSelectors: true
  includeTemplates: true
