apiVersion: v1
data:
  SIDECAR_IMAGE: |
    Z2hjci5pby9jbG91ZG5hdGl2ZS1wZy9wbHVnaW4tYmFybWFuLWNsb3VkLXNpZGVjYXI6dj
    AuMTAuMA==
kind: Secret
metadata:
  name: plugin-barman-cloud-t5844mh4gf
  namespace: cnpg-system
type: Opaque
