apiVersion: v1
data:
  SIDECAR_IMAGE: |
    Z2hjci5pby9jbG91ZG5hdGl2ZS1wZy9wbHVnaW4tYmFybWFuLWNsb3VkLXNpZGVjYXI6dj
    AuOS4w
kind: Secret
metadata:
  name: plugin-barman-cloud-dgkb8f78tm
  namespace: cnpg-system
type: Opaque
