apiVersion: v1
data:
  SIDECAR_IMAGE: |
    Z2hjci5pby9jbG91ZG5hdGl2ZS1wZy9wbHVnaW4tYmFybWFuLWNsb3VkLXNpZGVjYXI6dj
    AuMTEuMA==
kind: Secret
metadata:
  name: plugin-barman-cloud-52ggkcd52d
  namespace: cnpg-system
type: Opaque
