apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  labels:
    seigra.net/roles: readonly
  name: grafana-viewer
spec:
  deletionPolicy: Orphan
  forProvider:
    clientIdRef:
      name: grafana
    description: Can view dashboards, playlists, and query data sources.
    name: viewer
    realmIdRef:
      name: home
