apiVersion: v1
data:
  admin-password: TEhqVEpKZVVRR2VYcXo5S29idlFaU3M4WERvbDZaZ2c1S2NpdkxlSw==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: monitoring
type: Opaque
