apiVersion: v1
data:
  admin-password: UVdjOEI0QVYzcWxYcFNWZkJVRFBFa3dMZnNlME9sS280a055OUVnTw==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: monitoring
type: Opaque
