# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.2/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: registry
  name: harbor-registry
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: registry
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      containers:
      - name: registry
        image: goharbor/registry-photon:v2.14.0
        envFrom:
        - secretRef:
            name: harbor-registry
        ports:
        - containerPort: 5000
        - containerPort: 5001
        livenessProbe:
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /storage
          name: data
        - mountPath: /etc/registry/passwd
          name: passwd
          subPath: passwd
        - mountPath: /etc/registry/config.yml
          name: config
          subPath: config.yml
      - name: registryctl
        image: goharbor/harbor-registryctl:v2.14.0
        env:
        - name: CORE_SECRET
          valueFrom:
            secretKeyRef:
              key: CORE_SECRET
              name: harbor-core
        - name: JOBSERVICE_SECRET
          valueFrom:
            secretKeyRef:
              key: JOBSERVICE_SECRET
              name: harbor-jobservice
        envFrom:
        - secretRef:
            name: harbor-registry
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /storage
          name: data
        - mountPath: /etc/registry/config.yml
          name: config
          subPath: config.yml
        - mountPath: /etc/registryctl/config.yml
          name: config
          subPath: ctl-config.yml
      securityContext:
        fsGroup: 10000
        fsGroupChangePolicy: OnRootMismatch
        runAsUser: 10000
      terminationGracePeriodSeconds: 120
      volumes:
      - name: passwd
        secret:
          secretName: harbor-registry-passwd
          items:
          - key: passwd
            path: passwd
      - name: config
        configMap:
          name: harbor-registry-conf
      - name: data
        persistentVolumeClaim:
          claimName: harbor-registry-data
